[package]
name = "wegmans"
version = "0.1.0"
authors = ["doomy <alexanderpaullozada@gmail.com>"]

[dependencies]
reqwest = "0.8.4"
futures="*"
tokio-core="*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_qs = "0.3.0"